export const data = [
  {
    "attendance profile": "present",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "absent",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "weekend",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "holiday",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "on leave",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "present",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "present",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "present",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "absent",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "weekend",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "holiday",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "present",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "absent",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "weekend",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
  {
    "attendance profile": "holiday",
    department: "business development",
    "direct Manager": "Mohamed tarek",
    email: "hazem@gmail.com",
    name: "Hazem Mohamed",
    office: "arabic localizer",
    phone: "01234567899",
    position: "HR head",
    role: "employee",
    "Start Date": "2022-08-12",
    workHome: "on",
  },
];
